/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DriverRouteImport } from './routes/driver'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OwnerIndexRouteImport } from './routes/owner.index'
import { Route as DriverIndexRouteImport } from './routes/driver.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as DriverSearchRouteImport } from './routes/driver.search'
import { Route as DriverBookingsRouteImport } from './routes/driver.bookings'
import { Route as OwnerParkingNewRouteImport } from './routes/owner.parking.new'
import { Route as OwnerParkingParkingIdRouteImport } from './routes/owner.parking.$parkingId'
import { Route as DriverParkingParkingIdRouteImport } from './routes/driver.parking.$parkingId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRoute = OwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverRoute = DriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerIndexRoute = OwnerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OwnerRoute,
} as any)
const DriverIndexRoute = DriverIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DriverRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const DriverSearchRoute = DriverSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => DriverRoute,
} as any)
const DriverBookingsRoute = DriverBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => DriverRoute,
} as any)
const OwnerParkingNewRoute = OwnerParkingNewRouteImport.update({
  id: '/parking/new',
  path: '/parking/new',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerParkingParkingIdRoute = OwnerParkingParkingIdRouteImport.update({
  id: '/parking/$parkingId',
  path: '/parking/$parkingId',
  getParentRoute: () => OwnerRoute,
} as any)
const DriverParkingParkingIdRoute = DriverParkingParkingIdRouteImport.update({
  id: '/parking/$parkingId',
  path: '/parking/$parkingId',
  getParentRoute: () => DriverRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/driver': typeof DriverRouteWithChildren
  '/login': typeof LoginRoute
  '/owner': typeof OwnerRouteWithChildren
  '/register': typeof RegisterRoute
  '/driver/bookings': typeof DriverBookingsRoute
  '/driver/search': typeof DriverSearchRoute
  '/admin/': typeof AdminIndexRoute
  '/driver/': typeof DriverIndexRoute
  '/owner/': typeof OwnerIndexRoute
  '/driver/parking/$parkingId': typeof DriverParkingParkingIdRoute
  '/owner/parking/$parkingId': typeof OwnerParkingParkingIdRoute
  '/owner/parking/new': typeof OwnerParkingNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/driver/bookings': typeof DriverBookingsRoute
  '/driver/search': typeof DriverSearchRoute
  '/admin': typeof AdminIndexRoute
  '/driver': typeof DriverIndexRoute
  '/owner': typeof OwnerIndexRoute
  '/driver/parking/$parkingId': typeof DriverParkingParkingIdRoute
  '/owner/parking/$parkingId': typeof OwnerParkingParkingIdRoute
  '/owner/parking/new': typeof OwnerParkingNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/driver': typeof DriverRouteWithChildren
  '/login': typeof LoginRoute
  '/owner': typeof OwnerRouteWithChildren
  '/register': typeof RegisterRoute
  '/driver/bookings': typeof DriverBookingsRoute
  '/driver/search': typeof DriverSearchRoute
  '/admin/': typeof AdminIndexRoute
  '/driver/': typeof DriverIndexRoute
  '/owner/': typeof OwnerIndexRoute
  '/driver/parking/$parkingId': typeof DriverParkingParkingIdRoute
  '/owner/parking/$parkingId': typeof OwnerParkingParkingIdRoute
  '/owner/parking/new': typeof OwnerParkingNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/driver'
    | '/login'
    | '/owner'
    | '/register'
    | '/driver/bookings'
    | '/driver/search'
    | '/admin/'
    | '/driver/'
    | '/owner/'
    | '/driver/parking/$parkingId'
    | '/owner/parking/$parkingId'
    | '/owner/parking/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/driver/bookings'
    | '/driver/search'
    | '/admin'
    | '/driver'
    | '/owner'
    | '/driver/parking/$parkingId'
    | '/owner/parking/$parkingId'
    | '/owner/parking/new'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/driver'
    | '/login'
    | '/owner'
    | '/register'
    | '/driver/bookings'
    | '/driver/search'
    | '/admin/'
    | '/driver/'
    | '/owner/'
    | '/driver/parking/$parkingId'
    | '/owner/parking/$parkingId'
    | '/owner/parking/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DriverRoute: typeof DriverRouteWithChildren
  LoginRoute: typeof LoginRoute
  OwnerRoute: typeof OwnerRouteWithChildren
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver': {
      id: '/driver'
      path: '/driver'
      fullPath: '/driver'
      preLoaderRoute: typeof DriverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/': {
      id: '/owner/'
      path: '/'
      fullPath: '/owner/'
      preLoaderRoute: typeof OwnerIndexRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/driver/': {
      id: '/driver/'
      path: '/'
      fullPath: '/driver/'
      preLoaderRoute: typeof DriverIndexRouteImport
      parentRoute: typeof DriverRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/driver/search': {
      id: '/driver/search'
      path: '/search'
      fullPath: '/driver/search'
      preLoaderRoute: typeof DriverSearchRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/bookings': {
      id: '/driver/bookings'
      path: '/bookings'
      fullPath: '/driver/bookings'
      preLoaderRoute: typeof DriverBookingsRouteImport
      parentRoute: typeof DriverRoute
    }
    '/owner/parking/new': {
      id: '/owner/parking/new'
      path: '/parking/new'
      fullPath: '/owner/parking/new'
      preLoaderRoute: typeof OwnerParkingNewRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/parking/$parkingId': {
      id: '/owner/parking/$parkingId'
      path: '/parking/$parkingId'
      fullPath: '/owner/parking/$parkingId'
      preLoaderRoute: typeof OwnerParkingParkingIdRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/driver/parking/$parkingId': {
      id: '/driver/parking/$parkingId'
      path: '/parking/$parkingId'
      fullPath: '/driver/parking/$parkingId'
      preLoaderRoute: typeof DriverParkingParkingIdRouteImport
      parentRoute: typeof DriverRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DriverRouteChildren {
  DriverBookingsRoute: typeof DriverBookingsRoute
  DriverSearchRoute: typeof DriverSearchRoute
  DriverIndexRoute: typeof DriverIndexRoute
  DriverParkingParkingIdRoute: typeof DriverParkingParkingIdRoute
}

const DriverRouteChildren: DriverRouteChildren = {
  DriverBookingsRoute: DriverBookingsRoute,
  DriverSearchRoute: DriverSearchRoute,
  DriverIndexRoute: DriverIndexRoute,
  DriverParkingParkingIdRoute: DriverParkingParkingIdRoute,
}

const DriverRouteWithChildren =
  DriverRoute._addFileChildren(DriverRouteChildren)

interface OwnerRouteChildren {
  OwnerIndexRoute: typeof OwnerIndexRoute
  OwnerParkingParkingIdRoute: typeof OwnerParkingParkingIdRoute
  OwnerParkingNewRoute: typeof OwnerParkingNewRoute
}

const OwnerRouteChildren: OwnerRouteChildren = {
  OwnerIndexRoute: OwnerIndexRoute,
  OwnerParkingParkingIdRoute: OwnerParkingParkingIdRoute,
  OwnerParkingNewRoute: OwnerParkingNewRoute,
}

const OwnerRouteWithChildren = OwnerRoute._addFileChildren(OwnerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DriverRoute: DriverRouteWithChildren,
  LoginRoute: LoginRoute,
  OwnerRoute: OwnerRouteWithChildren,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
